// Code generated by protoc-gen-go.
// source: grpcreplica.proto
// DO NOT EDIT!

package replica

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Status int32

const (
	Status_NONE           Status = 0
	Status_PREACCEPTED    Status = 1
	Status_PREACCEPTED_EQ Status = 2
	Status_ACCEPTED       Status = 3
	Status_COMMITTED      Status = 4
	Status_EXECUTED       Status = 5
)

var Status_name = map[int32]string{
	0: "NONE",
	1: "PREACCEPTED",
	2: "PREACCEPTED_EQ",
	3: "ACCEPTED",
	4: "COMMITTED",
	5: "EXECUTED",
}
var Status_value = map[string]int32{
	"NONE":           0,
	"PREACCEPTED":    1,
	"PREACCEPTED_EQ": 2,
	"ACCEPTED":       3,
	"COMMITTED":      4,
	"EXECUTED":       5,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type Command_Operation int32

const (
	Command_NOP    Command_Operation = 0
	Command_PUT    Command_Operation = 1
	Command_GET    Command_Operation = 2
	Command_DELETE Command_Operation = 3
	Command_RLOCK  Command_Operation = 4
	Command_WLOCK  Command_Operation = 5
)

var Command_Operation_name = map[int32]string{
	0: "NOP",
	1: "PUT",
	2: "GET",
	3: "DELETE",
	4: "RLOCK",
	5: "WLOCK",
}
var Command_Operation_value = map[string]int32{
	"NOP":    0,
	"PUT":    1,
	"GET":    2,
	"DELETE": 3,
	"RLOCK":  4,
	"WLOCK":  5,
}

func (x Command_Operation) String() string {
	return proto.EnumName(Command_Operation_name, int32(x))
}
func (Command_Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type Command struct {
	Operation Command_Operation `protobuf:"varint,1,opt,name=operation,enum=replica.Command_Operation" json:"operation,omitempty"`
	Key       string            `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value     []byte            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type ClientProposal struct {
	CommandId int32    `protobuf:"varint,1,opt,name=command_id" json:"command_id,omitempty"`
	Command   *Command `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	Timestamp int64    `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ClientProposal) Reset()                    { *m = ClientProposal{} }
func (m *ClientProposal) String() string            { return proto.CompactTextString(m) }
func (*ClientProposal) ProtoMessage()               {}
func (*ClientProposal) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ClientProposal) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type ProposalReply struct {
	Ok      bool  `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Command int32 `protobuf:"varint,2,opt,name=command" json:"command,omitempty"`
}

func (m *ProposalReply) Reset()                    { *m = ProposalReply{} }
func (m *ProposalReply) String() string            { return proto.CompactTextString(m) }
func (*ProposalReply) ProtoMessage()               {}
func (*ProposalReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type ProposalReplyTS struct {
	Ok        bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Command   int32  `protobuf:"varint,2,opt,name=command" json:"command,omitempty"`
	Value     []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ProposalReplyTS) Reset()                    { *m = ProposalReplyTS{} }
func (m *ProposalReplyTS) String() string            { return proto.CompactTextString(m) }
func (*ProposalReplyTS) ProtoMessage()               {}
func (*ProposalReplyTS) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type ProposalRead struct {
	CommandId int32    `protobuf:"varint,1,opt,name=command_id" json:"command_id,omitempty"`
	Command   *Command `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	Key       string   `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
}

func (m *ProposalRead) Reset()                    { *m = ProposalRead{} }
func (m *ProposalRead) String() string            { return proto.CompactTextString(m) }
func (*ProposalRead) ProtoMessage()               {}
func (*ProposalRead) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ProposalRead) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type ProposalReadReply struct {
	Command int32  `protobuf:"varint,1,opt,name=command" json:"command,omitempty"`
	Ok      int32  `protobuf:"varint,2,opt,name=ok" json:"ok,omitempty"`
	Value   []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *ProposalReadReply) Reset()                    { *m = ProposalReadReply{} }
func (m *ProposalReadReply) String() string            { return proto.CompactTextString(m) }
func (*ProposalReadReply) ProtoMessage()               {}
func (*ProposalReadReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type Beacon struct {
	Replica   int32  `protobuf:"varint,2,opt,name=replica" json:"replica,omitempty"`
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Beacon) Reset()                    { *m = Beacon{} }
func (m *Beacon) String() string            { return proto.CompactTextString(m) }
func (*Beacon) ProtoMessage()               {}
func (*Beacon) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

type BeaconReply struct {
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Replica   int32  `protobuf:"varint,2,opt,name=replica" json:"replica,omitempty"`
}

func (m *BeaconReply) Reset()                    { *m = BeaconReply{} }
func (m *BeaconReply) String() string            { return proto.CompactTextString(m) }
func (*BeaconReply) ProtoMessage()               {}
func (*BeaconReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type PingArgs struct {
	ActAsLeader int32 `protobuf:"varint,1,opt,name=act_as_leader" json:"act_as_leader,omitempty"`
}

func (m *PingArgs) Reset()                    { *m = PingArgs{} }
func (m *PingArgs) String() string            { return proto.CompactTextString(m) }
func (*PingArgs) ProtoMessage()               {}
func (*PingArgs) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type Preparation struct {
	Leader   int32 `protobuf:"varint,1,opt,name=leader" json:"leader,omitempty"`
	Replica  int32 `protobuf:"varint,2,opt,name=replica" json:"replica,omitempty"`
	Instance int32 `protobuf:"varint,3,opt,name=instance" json:"instance,omitempty"`
	Ballot   int32 `protobuf:"varint,4,opt,name=ballot" json:"ballot,omitempty"`
}

func (m *Preparation) Reset()                    { *m = Preparation{} }
func (m *Preparation) String() string            { return proto.CompactTextString(m) }
func (*Preparation) ProtoMessage()               {}
func (*Preparation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type PreparationReply struct {
	Acceptor int32      `protobuf:"varint,1,opt,name=acceptor" json:"acceptor,omitempty"`
	Replica  int32      `protobuf:"varint,2,opt,name=replica" json:"replica,omitempty"`
	Instance int32      `protobuf:"varint,3,opt,name=instance" json:"instance,omitempty"`
	Ok       bool       `protobuf:"varint,4,opt,name=ok" json:"ok,omitempty"`
	Ballot   int32      `protobuf:"varint,5,opt,name=ballot" json:"ballot,omitempty"`
	Status   Status     `protobuf:"varint,6,opt,name=status,enum=replica.Status" json:"status,omitempty"`
	Commands []*Command `protobuf:"bytes,7,rep,name=commands" json:"commands,omitempty"`
	Seq      int32      `protobuf:"varint,8,opt,name=seq" json:"seq,omitempty"`
	Deps     []int32    `protobuf:"varint,9,rep,packed,name=deps" json:"deps,omitempty"`
}

func (m *PreparationReply) Reset()                    { *m = PreparationReply{} }
func (m *PreparationReply) String() string            { return proto.CompactTextString(m) }
func (*PreparationReply) ProtoMessage()               {}
func (*PreparationReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *PreparationReply) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

type PreAcceptance struct {
	Leader   int32      `protobuf:"varint,1,opt,name=leader" json:"leader,omitempty"`
	Replica  int32      `protobuf:"varint,2,opt,name=replica" json:"replica,omitempty"`
	Instance int32      `protobuf:"varint,3,opt,name=instance" json:"instance,omitempty"`
	Ballot   int32      `protobuf:"varint,4,opt,name=ballot" json:"ballot,omitempty"`
	Commands []*Command `protobuf:"bytes,5,rep,name=commands" json:"commands,omitempty"`
	Seq      int32      `protobuf:"varint,6,opt,name=seq" json:"seq,omitempty"`
	Deps     []int32    `protobuf:"varint,7,rep,packed,name=deps" json:"deps,omitempty"`
}

func (m *PreAcceptance) Reset()                    { *m = PreAcceptance{} }
func (m *PreAcceptance) String() string            { return proto.CompactTextString(m) }
func (*PreAcceptance) ProtoMessage()               {}
func (*PreAcceptance) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *PreAcceptance) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

type PreAcceptanceReply struct {
	Replica       int32   `protobuf:"varint,1,opt,name=replica" json:"replica,omitempty"`
	Instance      int32   `protobuf:"varint,2,opt,name=instance" json:"instance,omitempty"`
	Ok            bool    `protobuf:"varint,3,opt,name=ok" json:"ok,omitempty"`
	Ballot        int32   `protobuf:"varint,4,opt,name=ballot" json:"ballot,omitempty"`
	Seq           int32   `protobuf:"varint,5,opt,name=seq" json:"seq,omitempty"`
	Deps          []int32 `protobuf:"varint,6,rep,packed,name=deps" json:"deps,omitempty"`
	CommittedDeps []int32 `protobuf:"varint,7,rep,packed,name=committed_deps" json:"committed_deps,omitempty"`
}

func (m *PreAcceptanceReply) Reset()                    { *m = PreAcceptanceReply{} }
func (m *PreAcceptanceReply) String() string            { return proto.CompactTextString(m) }
func (*PreAcceptanceReply) ProtoMessage()               {}
func (*PreAcceptanceReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

type PreAcceptanceOk struct {
	Instance int32 `protobuf:"varint,1,opt,name=instance" json:"instance,omitempty"`
}

func (m *PreAcceptanceOk) Reset()                    { *m = PreAcceptanceOk{} }
func (m *PreAcceptanceOk) String() string            { return proto.CompactTextString(m) }
func (*PreAcceptanceOk) ProtoMessage()               {}
func (*PreAcceptanceOk) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

type Acceptance struct {
	Leader   int32   `protobuf:"varint,1,opt,name=leader" json:"leader,omitempty"`
	Replica  int32   `protobuf:"varint,2,opt,name=replica" json:"replica,omitempty"`
	Instance int32   `protobuf:"varint,3,opt,name=instance" json:"instance,omitempty"`
	Ballot   int32   `protobuf:"varint,4,opt,name=ballot" json:"ballot,omitempty"`
	Count    int32   `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
	Seq      int32   `protobuf:"varint,6,opt,name=seq" json:"seq,omitempty"`
	Deps     []int32 `protobuf:"varint,7,rep,packed,name=deps" json:"deps,omitempty"`
}

func (m *Acceptance) Reset()                    { *m = Acceptance{} }
func (m *Acceptance) String() string            { return proto.CompactTextString(m) }
func (*Acceptance) ProtoMessage()               {}
func (*Acceptance) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

type AcceptanceReply struct {
	Replica  int32 `protobuf:"varint,1,opt,name=replica" json:"replica,omitempty"`
	Instance int32 `protobuf:"varint,2,opt,name=instance" json:"instance,omitempty"`
	Ok       bool  `protobuf:"varint,3,opt,name=ok" json:"ok,omitempty"`
	Ballot   int32 `protobuf:"varint,4,opt,name=ballot" json:"ballot,omitempty"`
}

func (m *AcceptanceReply) Reset()                    { *m = AcceptanceReply{} }
func (m *AcceptanceReply) String() string            { return proto.CompactTextString(m) }
func (*AcceptanceReply) ProtoMessage()               {}
func (*AcceptanceReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

type TryCommit struct {
	Leader   int32      `protobuf:"varint,1,opt,name=leader" json:"leader,omitempty"`
	Replica  int32      `protobuf:"varint,2,opt,name=replica" json:"replica,omitempty"`
	Instance int32      `protobuf:"varint,3,opt,name=instance" json:"instance,omitempty"`
	Commands []*Command `protobuf:"bytes,4,rep,name=commands" json:"commands,omitempty"`
	Seq      int32      `protobuf:"varint,5,opt,name=seq" json:"seq,omitempty"`
	Deps     []int32    `protobuf:"varint,6,rep,packed,name=deps" json:"deps,omitempty"`
}

func (m *TryCommit) Reset()                    { *m = TryCommit{} }
func (m *TryCommit) String() string            { return proto.CompactTextString(m) }
func (*TryCommit) ProtoMessage()               {}
func (*TryCommit) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *TryCommit) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

type TryCommitShort struct {
	Leader   int32   `protobuf:"varint,1,opt,name=leader" json:"leader,omitempty"`
	Replica  int32   `protobuf:"varint,2,opt,name=replica" json:"replica,omitempty"`
	Instance int32   `protobuf:"varint,3,opt,name=instance" json:"instance,omitempty"`
	Count    int32   `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	Seq      int32   `protobuf:"varint,5,opt,name=seq" json:"seq,omitempty"`
	Deps     []int32 `protobuf:"varint,6,rep,packed,name=deps" json:"deps,omitempty"`
}

func (m *TryCommitShort) Reset()                    { *m = TryCommitShort{} }
func (m *TryCommitShort) String() string            { return proto.CompactTextString(m) }
func (*TryCommitShort) ProtoMessage()               {}
func (*TryCommitShort) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

type TryPreAcceptance struct {
	Leader   int32      `protobuf:"varint,1,opt,name=leader" json:"leader,omitempty"`
	Replica  int32      `protobuf:"varint,2,opt,name=replica" json:"replica,omitempty"`
	Instance int32      `protobuf:"varint,3,opt,name=instance" json:"instance,omitempty"`
	Ballot   int32      `protobuf:"varint,4,opt,name=ballot" json:"ballot,omitempty"`
	Commands []*Command `protobuf:"bytes,5,rep,name=commands" json:"commands,omitempty"`
	Seq      int32      `protobuf:"varint,6,opt,name=seq" json:"seq,omitempty"`
	Deps     []int32    `protobuf:"varint,7,rep,packed,name=deps" json:"deps,omitempty"`
}

func (m *TryPreAcceptance) Reset()                    { *m = TryPreAcceptance{} }
func (m *TryPreAcceptance) String() string            { return proto.CompactTextString(m) }
func (*TryPreAcceptance) ProtoMessage()               {}
func (*TryPreAcceptance) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *TryPreAcceptance) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

type TryPreAcceptanceReply struct {
	Acceptor         int32  `protobuf:"varint,1,opt,name=acceptor" json:"acceptor,omitempty"`
	Replica          int32  `protobuf:"varint,2,opt,name=replica" json:"replica,omitempty"`
	Instance         int32  `protobuf:"varint,3,opt,name=instance" json:"instance,omitempty"`
	Ok               bool   `protobuf:"varint,4,opt,name=ok" json:"ok,omitempty"`
	Ballot           int32  `protobuf:"varint,5,opt,name=ballot" json:"ballot,omitempty"`
	ConflictReplica  int32  `protobuf:"varint,6,opt,name=conflict_replica" json:"conflict_replica,omitempty"`
	ConflictInstance int32  `protobuf:"varint,7,opt,name=conflict_instance" json:"conflict_instance,omitempty"`
	ConflictStatus   Status `protobuf:"varint,8,opt,name=conflict_status,enum=replica.Status" json:"conflict_status,omitempty"`
}

func (m *TryPreAcceptanceReply) Reset()                    { *m = TryPreAcceptanceReply{} }
func (m *TryPreAcceptanceReply) String() string            { return proto.CompactTextString(m) }
func (*TryPreAcceptanceReply) ProtoMessage()               {}
func (*TryPreAcceptanceReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func init() {
	proto.RegisterType((*Empty)(nil), "replica.Empty")
	proto.RegisterType((*Command)(nil), "replica.Command")
	proto.RegisterType((*ClientProposal)(nil), "replica.ClientProposal")
	proto.RegisterType((*ProposalReply)(nil), "replica.ProposalReply")
	proto.RegisterType((*ProposalReplyTS)(nil), "replica.ProposalReplyTS")
	proto.RegisterType((*ProposalRead)(nil), "replica.ProposalRead")
	proto.RegisterType((*ProposalReadReply)(nil), "replica.ProposalReadReply")
	proto.RegisterType((*Beacon)(nil), "replica.Beacon")
	proto.RegisterType((*BeaconReply)(nil), "replica.BeaconReply")
	proto.RegisterType((*PingArgs)(nil), "replica.PingArgs")
	proto.RegisterType((*Preparation)(nil), "replica.Preparation")
	proto.RegisterType((*PreparationReply)(nil), "replica.PreparationReply")
	proto.RegisterType((*PreAcceptance)(nil), "replica.PreAcceptance")
	proto.RegisterType((*PreAcceptanceReply)(nil), "replica.PreAcceptanceReply")
	proto.RegisterType((*PreAcceptanceOk)(nil), "replica.PreAcceptanceOk")
	proto.RegisterType((*Acceptance)(nil), "replica.Acceptance")
	proto.RegisterType((*AcceptanceReply)(nil), "replica.AcceptanceReply")
	proto.RegisterType((*TryCommit)(nil), "replica.TryCommit")
	proto.RegisterType((*TryCommitShort)(nil), "replica.TryCommitShort")
	proto.RegisterType((*TryPreAcceptance)(nil), "replica.TryPreAcceptance")
	proto.RegisterType((*TryPreAcceptanceReply)(nil), "replica.TryPreAcceptanceReply")
	proto.RegisterEnum("replica.Status", Status_name, Status_value)
	proto.RegisterEnum("replica.Command_Operation", Command_Operation_name, Command_Operation_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for GrpcReplica service

type GrpcReplicaClient interface {
	Ping(ctx context.Context, in *Beacon, opts ...grpc.CallOption) (*Empty, error)
	ReplyPing(ctx context.Context, in *BeaconReply, opts ...grpc.CallOption) (*Empty, error)
	ProposeStream(ctx context.Context, opts ...grpc.CallOption) (GrpcReplica_ProposeStreamClient, error)
	Propose(ctx context.Context, in *ClientProposal, opts ...grpc.CallOption) (*Empty, error)
	ReplyPropose(ctx context.Context, in *ProposalReply, opts ...grpc.CallOption) (*Empty, error)
	ReplyProposeTS(ctx context.Context, in *ProposalReplyTS, opts ...grpc.CallOption) (*Empty, error)
	ProposeAndRead(ctx context.Context, in *ProposalRead, opts ...grpc.CallOption) (*Empty, error)
	ReplyProposeAndRead(ctx context.Context, in *ProposalReadReply, opts ...grpc.CallOption) (*Empty, error)
	Prepare(ctx context.Context, in *Preparation, opts ...grpc.CallOption) (*Empty, error)
	ReplyPrepare(ctx context.Context, in *PreparationReply, opts ...grpc.CallOption) (*Empty, error)
	TryPreAccept(ctx context.Context, in *TryPreAcceptance, opts ...grpc.CallOption) (*Empty, error)
	ReplyTryPreAccept(ctx context.Context, in *TryPreAcceptanceReply, opts ...grpc.CallOption) (*Empty, error)
	PreAccept(ctx context.Context, in *PreAcceptance, opts ...grpc.CallOption) (*Empty, error)
	ReplyPreAccept(ctx context.Context, in *PreAcceptanceReply, opts ...grpc.CallOption) (*Empty, error)
	PreAcceptOK(ctx context.Context, in *PreAcceptanceOk, opts ...grpc.CallOption) (*Empty, error)
	Accept(ctx context.Context, in *Acceptance, opts ...grpc.CallOption) (*Empty, error)
	ReplyAccept(ctx context.Context, in *AcceptanceReply, opts ...grpc.CallOption) (*Empty, error)
	Commit(ctx context.Context, in *TryCommit, opts ...grpc.CallOption) (*Empty, error)
	CommitShort(ctx context.Context, in *TryCommitShort, opts ...grpc.CallOption) (*Empty, error)
}

type grpcReplicaClient struct {
	cc *grpc.ClientConn
}

func NewGrpcReplicaClient(cc *grpc.ClientConn) GrpcReplicaClient {
	return &grpcReplicaClient{cc}
}

func (c *grpcReplicaClient) Ping(ctx context.Context, in *Beacon, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) ReplyPing(ctx context.Context, in *BeaconReply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/ReplyPing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) ProposeStream(ctx context.Context, opts ...grpc.CallOption) (GrpcReplica_ProposeStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GrpcReplica_serviceDesc.Streams[0], c.cc, "/replica.GrpcReplica/ProposeStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcReplicaProposeStreamClient{stream}
	return x, nil
}

type GrpcReplica_ProposeStreamClient interface {
	Send(*ClientProposal) error
	Recv() (*ProposalReplyTS, error)
	grpc.ClientStream
}

type grpcReplicaProposeStreamClient struct {
	grpc.ClientStream
}

func (x *grpcReplicaProposeStreamClient) Send(m *ClientProposal) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcReplicaProposeStreamClient) Recv() (*ProposalReplyTS, error) {
	m := new(ProposalReplyTS)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grpcReplicaClient) Propose(ctx context.Context, in *ClientProposal, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/Propose", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) ReplyPropose(ctx context.Context, in *ProposalReply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/ReplyPropose", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) ReplyProposeTS(ctx context.Context, in *ProposalReplyTS, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/ReplyProposeTS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) ProposeAndRead(ctx context.Context, in *ProposalRead, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/ProposeAndRead", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) ReplyProposeAndRead(ctx context.Context, in *ProposalReadReply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/ReplyProposeAndRead", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) Prepare(ctx context.Context, in *Preparation, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/Prepare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) ReplyPrepare(ctx context.Context, in *PreparationReply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/ReplyPrepare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) TryPreAccept(ctx context.Context, in *TryPreAcceptance, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/TryPreAccept", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) ReplyTryPreAccept(ctx context.Context, in *TryPreAcceptanceReply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/ReplyTryPreAccept", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) PreAccept(ctx context.Context, in *PreAcceptance, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/PreAccept", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) ReplyPreAccept(ctx context.Context, in *PreAcceptanceReply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/ReplyPreAccept", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) PreAcceptOK(ctx context.Context, in *PreAcceptanceOk, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/PreAcceptOK", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) Accept(ctx context.Context, in *Acceptance, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/Accept", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) ReplyAccept(ctx context.Context, in *AcceptanceReply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/ReplyAccept", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) Commit(ctx context.Context, in *TryCommit, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/Commit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcReplicaClient) CommitShort(ctx context.Context, in *TryCommitShort, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcReplica/CommitShort", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GrpcReplica service

type GrpcReplicaServer interface {
	Ping(context.Context, *Beacon) (*Empty, error)
	ReplyPing(context.Context, *BeaconReply) (*Empty, error)
	ProposeStream(GrpcReplica_ProposeStreamServer) error
	Propose(context.Context, *ClientProposal) (*Empty, error)
	ReplyPropose(context.Context, *ProposalReply) (*Empty, error)
	ReplyProposeTS(context.Context, *ProposalReplyTS) (*Empty, error)
	ProposeAndRead(context.Context, *ProposalRead) (*Empty, error)
	ReplyProposeAndRead(context.Context, *ProposalReadReply) (*Empty, error)
	Prepare(context.Context, *Preparation) (*Empty, error)
	ReplyPrepare(context.Context, *PreparationReply) (*Empty, error)
	TryPreAccept(context.Context, *TryPreAcceptance) (*Empty, error)
	ReplyTryPreAccept(context.Context, *TryPreAcceptanceReply) (*Empty, error)
	PreAccept(context.Context, *PreAcceptance) (*Empty, error)
	ReplyPreAccept(context.Context, *PreAcceptanceReply) (*Empty, error)
	PreAcceptOK(context.Context, *PreAcceptanceOk) (*Empty, error)
	Accept(context.Context, *Acceptance) (*Empty, error)
	ReplyAccept(context.Context, *AcceptanceReply) (*Empty, error)
	Commit(context.Context, *TryCommit) (*Empty, error)
	CommitShort(context.Context, *TryCommitShort) (*Empty, error)
}

func RegisterGrpcReplicaServer(s *grpc.Server, srv GrpcReplicaServer) {
	s.RegisterService(&_GrpcReplica_serviceDesc, srv)
}

func _GrpcReplica_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Beacon)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).Ping(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_ReplyPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BeaconReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).ReplyPing(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_ProposeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcReplicaServer).ProposeStream(&grpcReplicaProposeStreamServer{stream})
}

type GrpcReplica_ProposeStreamServer interface {
	Send(*ProposalReplyTS) error
	Recv() (*ClientProposal, error)
	grpc.ServerStream
}

type grpcReplicaProposeStreamServer struct {
	grpc.ServerStream
}

func (x *grpcReplicaProposeStreamServer) Send(m *ProposalReplyTS) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcReplicaProposeStreamServer) Recv() (*ClientProposal, error) {
	m := new(ClientProposal)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GrpcReplica_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ClientProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).Propose(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_ReplyPropose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ProposalReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).ReplyPropose(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_ReplyProposeTS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ProposalReplyTS)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).ReplyProposeTS(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_ProposeAndRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ProposalRead)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).ProposeAndRead(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_ReplyProposeAndRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ProposalReadReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).ReplyProposeAndRead(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Preparation)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).Prepare(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_ReplyPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(PreparationReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).ReplyPrepare(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_TryPreAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(TryPreAcceptance)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).TryPreAccept(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_ReplyTryPreAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(TryPreAcceptanceReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).ReplyTryPreAccept(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_PreAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(PreAcceptance)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).PreAccept(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_ReplyPreAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(PreAcceptanceReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).ReplyPreAccept(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_PreAcceptOK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(PreAcceptanceOk)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).PreAcceptOK(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Acceptance)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).Accept(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_ReplyAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AcceptanceReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).ReplyAccept(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(TryCommit)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).Commit(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GrpcReplica_CommitShort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(TryCommitShort)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcReplicaServer).CommitShort(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _GrpcReplica_serviceDesc = grpc.ServiceDesc{
	ServiceName: "replica.GrpcReplica",
	HandlerType: (*GrpcReplicaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GrpcReplica_Ping_Handler,
		},
		{
			MethodName: "ReplyPing",
			Handler:    _GrpcReplica_ReplyPing_Handler,
		},
		{
			MethodName: "Propose",
			Handler:    _GrpcReplica_Propose_Handler,
		},
		{
			MethodName: "ReplyPropose",
			Handler:    _GrpcReplica_ReplyPropose_Handler,
		},
		{
			MethodName: "ReplyProposeTS",
			Handler:    _GrpcReplica_ReplyProposeTS_Handler,
		},
		{
			MethodName: "ProposeAndRead",
			Handler:    _GrpcReplica_ProposeAndRead_Handler,
		},
		{
			MethodName: "ReplyProposeAndRead",
			Handler:    _GrpcReplica_ReplyProposeAndRead_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _GrpcReplica_Prepare_Handler,
		},
		{
			MethodName: "ReplyPrepare",
			Handler:    _GrpcReplica_ReplyPrepare_Handler,
		},
		{
			MethodName: "TryPreAccept",
			Handler:    _GrpcReplica_TryPreAccept_Handler,
		},
		{
			MethodName: "ReplyTryPreAccept",
			Handler:    _GrpcReplica_ReplyTryPreAccept_Handler,
		},
		{
			MethodName: "PreAccept",
			Handler:    _GrpcReplica_PreAccept_Handler,
		},
		{
			MethodName: "ReplyPreAccept",
			Handler:    _GrpcReplica_ReplyPreAccept_Handler,
		},
		{
			MethodName: "PreAcceptOK",
			Handler:    _GrpcReplica_PreAcceptOK_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _GrpcReplica_Accept_Handler,
		},
		{
			MethodName: "ReplyAccept",
			Handler:    _GrpcReplica_ReplyAccept_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _GrpcReplica_Commit_Handler,
		},
		{
			MethodName: "CommitShort",
			Handler:    _GrpcReplica_CommitShort_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProposeStream",
			Handler:       _GrpcReplica_ProposeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

var fileDescriptor1 = []byte{
	// 990 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x57, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x5e, 0x27, 0xfe, 0x3d, 0xd9, 0x4d, 0x9c, 0x29, 0x4b, 0xdd, 0x20, 0x41, 0x6b, 0x6e, 0x16,
	0x04, 0x0b, 0xdd, 0x82, 0x44, 0x05, 0x52, 0xb5, 0x75, 0xad, 0x16, 0xb5, 0xdd, 0x84, 0x6c, 0x2a,
	0x10, 0x37, 0x91, 0xd7, 0x31, 0x4b, 0xb4, 0x49, 0xec, 0x3a, 0x5e, 0xa4, 0xbd, 0xe0, 0x82, 0x17,
	0xe0, 0x0e, 0x89, 0x2b, 0x5e, 0x87, 0xf7, 0xe0, 0x49, 0x38, 0x9e, 0x19, 0x3b, 0xe3, 0x64, 0x1c,
	0x60, 0xb5, 0x48, 0xbd, 0x8b, 0xe7, 0x9c, 0xef, 0x7c, 0xdf, 0x7c, 0x67, 0xfe, 0x02, 0xdd, 0xf3,
	0x34, 0x09, 0xd3, 0x28, 0x99, 0x4d, 0xc3, 0xe0, 0x30, 0x49, 0xe3, 0x2c, 0x26, 0x06, 0xff, 0x74,
	0x0d, 0xd0, 0xfc, 0x79, 0x92, 0x5d, 0xb9, 0x7f, 0x28, 0x60, 0x78, 0xf1, 0x7c, 0x1e, 0x2c, 0x26,
	0xe4, 0x63, 0xb0, 0xe2, 0x24, 0x4a, 0x83, 0x6c, 0x1a, 0x2f, 0x1c, 0xe5, 0xae, 0x72, 0xd0, 0x3e,
	0xea, 0x1d, 0x16, 0x05, 0x78, 0xd2, 0x61, 0xbf, 0xc8, 0x20, 0x2d, 0x68, 0x5e, 0x44, 0x57, 0x4e,
	0x03, 0x13, 0x2d, 0xb2, 0x07, 0xda, 0x4f, 0xc1, 0xec, 0x32, 0x72, 0x9a, 0xf8, 0xb9, 0xeb, 0x3e,
	0x03, 0x6b, 0x95, 0x68, 0x40, 0xf3, 0xa4, 0x3f, 0xb0, 0x77, 0xf2, 0x1f, 0x83, 0x57, 0x23, 0x5b,
	0xc9, 0x7f, 0x3c, 0xf5, 0x47, 0x76, 0x83, 0x00, 0xe8, 0x4f, 0xfc, 0x17, 0xfe, 0xc8, 0xb7, 0x9b,
	0xc4, 0x02, 0x6d, 0xf8, 0xa2, 0xef, 0x3d, 0xb7, 0xd5, 0xfc, 0xe7, 0xb7, 0xf4, 0xa7, 0xe6, 0x7e,
	0x0f, 0x6d, 0x6f, 0x36, 0x8d, 0x16, 0xd9, 0x20, 0x8d, 0x93, 0x78, 0x19, 0xcc, 0x08, 0x82, 0x42,
	0x26, 0x66, 0x3c, 0x9d, 0x50, 0x9d, 0x1a, 0xb9, 0x07, 0x06, 0x1f, 0xa3, 0x7a, 0x5a, 0x47, 0xf6,
	0xba, 0x70, 0xd2, 0x05, 0x2b, 0x9b, 0xce, 0xa3, 0x65, 0x16, 0xcc, 0x13, 0xaa, 0xb2, 0xe9, 0x7e,
	0x04, 0x7b, 0x45, 0xd5, 0x21, 0x66, 0x5f, 0x61, 0xe5, 0x46, 0x7c, 0x41, 0x4b, 0x9a, 0xa4, 0x53,
	0x2d, 0xa9, 0xb9, 0x03, 0xe8, 0x54, 0xb2, 0x47, 0xa7, 0x5b, 0xf3, 0xd7, 0x2c, 0xa9, 0xf2, 0xab,
	0x94, 0x7f, 0x08, 0xbb, 0xab, 0x8a, 0xc1, 0xe4, 0xba, 0x33, 0xe3, 0x8d, 0xc8, 0x69, 0x2c, 0xf7,
	0x11, 0x74, 0xc5, 0x9a, 0x6c, 0x5e, 0x82, 0x36, 0x56, 0x95, 0x09, 0x97, 0xe9, 0x44, 0x53, 0xf4,
	0xc7, 0x51, 0x10, 0x62, 0xdf, 0x10, 0xc5, 0xa9, 0x78, 0x66, 0x65, 0x0a, 0x79, 0x21, 0xd5, 0xbd,
	0x0f, 0x2d, 0x96, 0xcd, 0x88, 0x36, 0x33, 0x36, 0xaa, 0xb8, 0xf7, 0xc0, 0x1c, 0x4c, 0x17, 0xe7,
	0xc7, 0xe9, 0xf9, 0x92, 0xec, 0xc3, 0x5e, 0x10, 0x66, 0xe3, 0x60, 0x39, 0x9e, 0xa1, 0xd8, 0x28,
	0x65, 0xf2, 0xd0, 0xea, 0xd6, 0x00, 0x41, 0x01, 0x5f, 0x40, 0x6d, 0xd0, 0xc5, 0xf0, 0xa6, 0x30,
	0x1b, 0xcc, 0xe9, 0x02, 0x49, 0x17, 0x21, 0x9b, 0x85, 0x96, 0x43, 0xce, 0x82, 0xd9, 0x2c, 0xce,
	0xa8, 0xd5, 0x9a, 0xfb, 0xa7, 0x02, 0xb6, 0x50, 0x92, 0xa9, 0x45, 0x58, 0x10, 0x86, 0x51, 0x92,
	0xc5, 0xff, 0xa1, 0x32, 0xb3, 0x4e, 0xa5, 0x3d, 0x5f, 0xb1, 0x68, 0x34, 0xf6, 0x1e, 0xe8, 0x98,
	0x9b, 0x5d, 0x2e, 0x1d, 0x9d, 0x6e, 0x9f, 0x4e, 0xd9, 0xab, 0x53, 0x3a, 0x4c, 0x5c, 0x30, 0x79,
	0x23, 0x96, 0x8e, 0x71, 0xb7, 0x59, 0xd7, 0xce, 0x65, 0xf4, 0xda, 0x31, 0x39, 0xbf, 0x3a, 0x89,
	0x92, 0xa5, 0x63, 0x61, 0xb2, 0xf6, 0xb8, 0x61, 0x2b, 0xee, 0x6f, 0x4a, 0xbe, 0x6a, 0xa3, 0x63,
	0x2a, 0x3c, 0xd7, 0x75, 0x03, 0xf6, 0x54, 0x74, 0x69, 0xdb, 0x75, 0xe9, 0x15, 0x5d, 0x46, 0xa9,
	0xeb, 0x57, 0x05, 0x48, 0x45, 0x57, 0xb9, 0xf4, 0x0a, 0x31, 0xca, 0x86, 0x98, 0x86, 0xe0, 0x68,
	0x73, 0xcd, 0x51, 0x26, 0x8c, 0x93, 0x6a, 0x15, 0x52, 0xbd, 0x20, 0x25, 0x3d, 0x68, 0xe7, 0xba,
	0xa7, 0x59, 0x16, 0x4d, 0xc6, 0x6b, 0x82, 0xde, 0xcf, 0xf7, 0xab, 0xa0, 0xa7, 0x7f, 0x51, 0xe1,
	0x66, 0x2b, 0xed, 0x67, 0x80, 0x9b, 0x75, 0x12, 0x77, 0x53, 0x18, 0x5f, 0x2e, 0x8a, 0x15, 0xf1,
	0x0f, 0xa6, 0xe1, 0x99, 0x72, 0xb3, 0x86, 0xb9, 0xbf, 0x28, 0x60, 0x8d, 0xd2, 0x2b, 0x8f, 0xba,
	0x72, 0x9d, 0x09, 0x89, 0x4b, 0x41, 0xdd, 0xbe, 0x14, 0x6a, 0xba, 0xe2, 0xbe, 0x86, 0x76, 0x29,
	0xe1, 0xf4, 0xc7, 0x38, 0xbd, 0x96, 0x8e, 0xd2, 0xc8, 0x7f, 0xb3, 0x10, 0xdc, 0xdf, 0x71, 0x7f,
	0x23, 0xe7, 0x9b, 0xb8, 0x31, 0xf0, 0xe8, 0xd9, 0x5f, 0x97, 0xf6, 0x3f, 0x9d, 0x3f, 0x0e, 0xd8,
	0x78, 0x14, 0xff, 0x80, 0xf8, 0x6c, 0x5c, 0xd4, 0x61, 0xb2, 0xee, 0x40, 0xb7, 0x8c, 0x94, 0x05,
	0x0d, 0x1a, 0x3a, 0x80, 0x4e, 0x19, 0xe2, 0xa7, 0x97, 0x29, 0x3d, 0xbd, 0x3e, 0x3c, 0x03, 0x9d,
	0x9f, 0x63, 0x26, 0xa8, 0x27, 0xfd, 0x13, 0x1f, 0xef, 0xf4, 0x0e, 0x1e, 0xd5, 0x43, 0xff, 0xd8,
	0xf3, 0xfc, 0xc1, 0xc8, 0x7f, 0x82, 0x5b, 0x92, 0x40, 0x5b, 0x18, 0x18, 0xfb, 0xdf, 0xe0, 0x35,
	0xbf, 0x0b, 0x66, 0x99, 0xd1, 0xc4, 0xce, 0x5a, 0x5e, 0xff, 0xe5, 0xcb, 0xaf, 0x47, 0xf9, 0xa7,
	0x9a, 0x07, 0xfd, 0xef, 0x7c, 0xef, 0x55, 0xfe, 0xa5, 0x1d, 0xfd, 0x65, 0x42, 0xeb, 0x29, 0x3e,
	0x5c, 0x86, 0x8c, 0x9a, 0x7c, 0x00, 0x6a, 0x7e, 0x5b, 0x90, 0x95, 0x18, 0x76, 0xdf, 0xf4, 0xda,
	0xe5, 0x00, 0x7b, 0xc9, 0xec, 0x90, 0x07, 0x60, 0x51, 0x5f, 0x69, 0xfe, 0x5b, 0x6b, 0xf9, 0x34,
	0x22, 0x01, 0x3d, 0x2b, 0xde, 0x00, 0xd1, 0x69, 0x96, 0x46, 0xc1, 0x9c, 0xdc, 0x5e, 0xf5, 0xb7,
	0xf2, 0xee, 0xe8, 0x39, 0x65, 0x60, 0xed, 0x19, 0xe0, 0xee, 0x1c, 0x28, 0x9f, 0x2a, 0xe4, 0x33,
	0x30, 0x78, 0xa5, 0xfa, 0x1a, 0x9b, 0xfc, 0x5f, 0xc0, 0x2e, 0x13, 0xcd, 0xa1, 0x6f, 0xcb, 0x59,
	0x24, 0xc8, 0xaf, 0xa0, 0x2d, 0x22, 0xf1, 0x39, 0x52, 0xab, 0x50, 0x82, 0x7e, 0x88, 0x6d, 0x62,
	0xc0, 0xe3, 0xc5, 0x84, 0xbe, 0x3e, 0xf6, 0x25, 0xe8, 0x60, 0x22, 0x81, 0x7a, 0x70, 0x4b, 0x24,
	0x2e, 0xf0, 0x3d, 0x29, 0xbe, 0x4e, 0xfd, 0xfd, 0xdc, 0xad, 0xfc, 0x3e, 0x8e, 0x84, 0x56, 0x09,
	0x37, 0xb4, 0x04, 0xf2, 0x65, 0x69, 0x15, 0xc3, 0xdd, 0x91, 0xe1, 0xea, 0xf8, 0x10, 0x2c, 0x6e,
	0x42, 0x01, 0xbc, 0xbe, 0x37, 0x25, 0x60, 0x1f, 0xba, 0xcc, 0x49, 0xb1, 0xc2, 0xbb, 0xb5, 0x15,
	0xea, 0x34, 0x7c, 0x0e, 0xd6, 0x0a, 0x2e, 0x36, 0x7a, 0x3b, 0xfb, 0xa3, 0xb2, 0xd1, 0x05, 0xf6,
	0x1d, 0x39, 0xb6, 0x8e, 0xf7, 0x21, 0x7d, 0x4e, 0xb1, 0xbc, 0xfe, 0xf3, 0xca, 0x32, 0xa9, 0xdc,
	0x8f, 0x12, 0xe8, 0x27, 0xa0, 0x73, 0xce, 0x5b, 0x65, 0x6c, 0xab, 0x58, 0xe4, 0xa2, 0x32, 0x38,
	0xca, 0x91, 0xa0, 0xea, 0x64, 0x1e, 0x82, 0xce, 0xaf, 0x2d, 0x22, 0x5a, 0xcb, 0xc6, 0xa4, 0x5b,
	0xa7, 0x25, 0xde, 0x31, 0xb7, 0x37, 0x41, 0x34, 0xb0, 0x89, 0x3c, 0xd3, 0xe9, 0xdf, 0xa1, 0x07,
	0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x52, 0x11, 0x76, 0xc6, 0x23, 0x0d, 0x00, 0x00,
}
