// Code generated by protoc-gen-go.
// source: grpcclient.proto
// DO NOT EDIT!

/*
Package replica is a generated protocol buffer package.

It is generated from these files:
	grpcclient.proto
	grpcreplica.proto

It has these top-level messages:
	Empty
	Command
	Proposal
	ProposalReply
	ProposalReplyTS
	ProposalRead
	ProposalReadReply
	Beacon
	BeaconReply
	PingArgs
	Preparation
	PreparationReply
	PreAcceptance
	PreAcceptanceReply
	PreAcceptanceOk
	Acceptance
	AcceptanceReply
	TryCommit
	TryCommitShort
	TryPreAcceptance
	TryPreAcceptanceReply
*/
package replica

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for GrpcClient service

type GrpcClientClient interface {
	ReplyProposeTS(ctx context.Context, in *ProposalReplyTS, opts ...grpc.CallOption) (*Empty, error)
}

type grpcClientClient struct {
	cc *grpc.ClientConn
}

func NewGrpcClientClient(cc *grpc.ClientConn) GrpcClientClient {
	return &grpcClientClient{cc}
}

func (c *grpcClientClient) ReplyProposeTS(ctx context.Context, in *ProposalReplyTS, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/replica.GrpcClient/ReplyProposeTS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GrpcClient service

type GrpcClientServer interface {
	ReplyProposeTS(context.Context, *ProposalReplyTS) (*Empty, error)
}

func RegisterGrpcClientServer(s *grpc.Server, srv GrpcClientServer) {
	s.RegisterService(&_GrpcClient_serviceDesc, srv)
}

func _GrpcClient_ReplyProposeTS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ProposalReplyTS)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GrpcClientServer).ReplyProposeTS(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _GrpcClient_serviceDesc = grpc.ServiceDesc{
	ServiceName: "replica.GrpcClient",
	HandlerType: (*GrpcClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplyProposeTS",
			Handler:    _GrpcClient_ReplyProposeTS_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x2f, 0x2a, 0x48,
	0x4e, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4a,
	0x2d, 0xc8, 0xc9, 0x4c, 0x4e, 0x94, 0x12, 0x04, 0x49, 0x41, 0x39, 0x10, 0x39, 0x23, 0x2f, 0x2e,
	0x2e, 0x77, 0xa0, 0xa0, 0x33, 0x58, 0xbd, 0x90, 0x0d, 0x17, 0x5f, 0x10, 0x50, 0xba, 0x32, 0xa0,
	0x28, 0xbf, 0x20, 0xbf, 0x38, 0x35, 0x24, 0x58, 0x48, 0x42, 0x0f, 0xa6, 0x1e, 0x22, 0x96, 0x98,
	0x03, 0x56, 0x10, 0x12, 0x2c, 0xc5, 0x07, 0x97, 0x71, 0xcd, 0x2d, 0x28, 0xa9, 0x54, 0x62, 0x48,
	0x62, 0x03, 0x1b, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x23, 0x58, 0x97, 0x5c, 0x82, 0x00,
	0x00, 0x00,
}
